IF
	True()
THEN
	RESPONSE #100
		CutSceneId("tthitomi")
		SetGlobal("ttKachikoSaved","GLOBAL",1)
		FadeToColor([20.0],0)
		Wait(1)
		ActionOverride("ttkachid",DestroySelf())
		CreateCreature("ttkachis",[1392.736],8)
		FadeFromColor([20.0],0)
		EndCutSceneMode()
		ForceSpell(Myself,TRANSFORMATION_DEATH)
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Yoshimo")
		Wait(3)
		StartDialogueNoSet(Player1)
END