// ToB Lovetalks

IF
	See("Yoshimo")
	!Dead("Yoshimo")
	CombatCounter(0)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck("Yoshimo",CD_STATE_NOTVALID)
	GlobalTimerExpired("ttKachikoRomanceTimerTOB","GLOBAL")
	OR(2)
		Global("ttKachikoRomanceTOB","GLOBAL",1)
		Global("ttKachikoRomanceTOB","GLOBAL",3)
THEN
	RESPONSE #100
		IncrementGlobal("ttKachikoRomanceTOB","GLOBAL",1)
		PlaySong(0)
		PlaySound("ttkachls")
		Interact("Yoshimo")
END