// ToB Lovetalks

IF
	See("Yoshimo")
	!Dead("Yoshimo")
	CombatCounter(0)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck("Yoshimo",CD_STATE_NOTVALID)
	GlobalTimerExpired("VP_KachikoRomanceTimerTOB","GLOBAL")
	OR(2)
		Global("VP_KachikoRomanceTOB","GLOBAL",1)
		Global("VP_KachikoRomanceTOB","GLOBAL",3)
THEN
	RESPONSE #100
		IncrementGlobal("VP_KachikoRomanceTOB","GLOBAL",1)
		PlaySong(0)
		PlaySound("vpkachls")
		Interact("Yoshimo")
END